apiVersion: imgpkg.carvel.dev/v1alpha1
kind: Bundle
metadata:
  name: fluent-bit
authors:
- name: Harsha Narayana
  email: harsha2k4@gmail.com
websites:
- url: https://fluentbit.io/
- url: https://github.com/fluent/fluent-bit/
